# Generated by Django 3.2.2 on 2022-05-05 03:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=250, unique=True, verbose_name='File Name')),
                ('dirname', models.CharField(max_length=250, verbose_name='File Dir')),
                ('path', models.CharField(max_length=250, verbose_name='File Path')),
                ('filesize', models.IntegerField(verbose_name='File Size')),
                ('duration', models.DecimalField(decimal_places=3, max_digits=10)),
                ('is_included', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(verbose_name='File Datetime')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
