# Generated by Django 3.2.2 on 2023-01-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='channels',
            field=models.IntegerField(default=0),
        ),
    ]
