# Generated by Django 3.2.2 on 2021-10-26 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batch', '0001_initial'),
        ('segment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='model_developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='segments',
            field=models.ManyToManyField(blank=True, related_name='batches', to='segment.Segment'),
        ),
    ]
