# Generated by Django 3.2.2 on 2022-05-03 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_alter_annotation_sound_id_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='offset',
        ),
    ]
