# Generated by Django 3.2.2 on 2021-12-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_file_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(max_length=250, unique=True, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=250, verbose_name='File Path'),
        ),
    ]
