# Generated by Django 3.2.2 on 2023-01-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='amplification',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AddField(
            model_name='batch',
            name='high_pass_freq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='low_pass_freq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='vmax',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AddField(
            model_name='batch',
            name='vmin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
