# Generated by Django 3.2.2 on 2023-01-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_auto_20230104_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='channel',
            field=models.IntegerField(default=0),
        ),
    ]
