# Generated by Django 3.2.2 on 2023-01-11 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0002_segment_model_developer'),
        ('batch', '0005_batch_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSegmentAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio_clips')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch.batch')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segment.segment')),
            ],
        ),
    ]
