# Generated by Django 3.2.2 on 2021-10-26 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batch', '0001_initial'),
        ('segment', '0001_initial'),
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch.batch'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segment.segment'),
        ),
    ]
