# Generated by Django 3.2.2 on 2022-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='sound_id_species',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
