# Generated by Django 3.2.2 on 2022-09-23 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatorprogress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
